apiVersion: v1
kind: Service
metadata:
  name: webapp-service-secret
  labels:
    app: webapp-service-secret
spec:
  selector:
    app: webapp-service-secret
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30082