apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color-secret
  labels: 
    app: webapp-service-secret
spec:
  containers:
  - name: simple-webapp-color-secret
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: APP_COLOR_SECRET
      valueFrom: 
        secretKeyRef:
          name: app-secret
          key: APP_COLOR_KEY