apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp-service
spec:
  selector:
    app: webapp-service
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080