apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color-configmap
  labels: 
    app: webapp-service-configmap
spec:
  containers:
  - name: simple-webapp-color-configmap
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: app-config
          key: APP_COLOR